export const REQUEST_REMOTE_ACTION = 'REQUEST_REMOTE_ACTION';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const SHOW_VALIDATED_ANSWER = 'SHOW_VALIDATED_ANSWER';
export const RECEIVE_QUIZ_QUESTION = 'RECEIVE_QUIZ_QUESTION';
export const RESET_QUIZ_QUESTION_AND_ANSWER = 'RESET_QUIZ_QUESTION_AND_ANSWER';
export const RECEIVE_ERROR_MESSAGE = 'RECEIVE_ERROR_MESSAGE';